// Study materials data structure
export const STUDY_MATERIALS = [
  {
    id: 1,
    title: 'CBSE Notes',
    description: 'Clear and simple chapter-wise notes for CBSE subjects. Perfect for better understanding of important concepts.',
    category: 'cbse',
    type: 'notes',
    exam: 'CBSE',
    class: ['class10', 'class12'],
    icon: '📚',
  },
  {
    id: 2,
    title: 'CBSE Sample Papers',
    description: 'Practice with the CBSE sample question papers. Understand the concepts and improve your confidence before exams.',
    category: 'cbse',
    type: 'papers',
    exam: 'CBSE',
    class: ['class10', 'class12'],
    icon: '📋',
  },
  {
    id: 3,
    title: 'CBSE Question Banks',
    description: 'Important questions collected from previous exams and textbooks. Useful for practicing and preparing for CBSE exams.',
    category: 'cbse',
    type: 'questions',
    exam: 'CBSE',
    class: ['class10', 'class12'],
    icon: '❓',
  },
  {
    id: 4,
    title: 'NEET Mock Tests',
    description: 'Important questions collected from previous exams and textbooks. Useful for practicing and preparing for NEET exams.',
    category: 'neet',
    type: 'mocks',
    exam: 'NEET',
    class: ['class12'],
    icon: '🧪',
  },
  {
    id: 5,
    title: 'NCERT Books',
    description: 'Access NCERT textbooks for different classes and subjects. Helpful for building strong basics and preparing for school exams.',
    category: 'boards',
    type: 'books',
    exam: 'Multiple',
    class: ['class10', 'class11', 'class12'],
    icon: '📖',
  },
  {
    id: 6,
    title: 'Class 10 Previous Papers',
    description: 'Practice previous year question papers for Class 10 exams. Understand important topics and improve exam preparation.',
    category: 'cbse',
    type: 'papers',
    exam: 'CBSE',
    class: ['class10'],
    icon: '📄',
  },
  {
    id: 7,
    title: 'NEET Biology Notes',
    description: 'Easy-to-understand biology notes based on NCERT topics. Great for quick revision and NEET exam preparation.',
    category: 'neet',
    type: 'notes',
    exam: 'NEET',
    class: ['class12'],
    icon: '🧬',
  },
  {
    id: 8,
    title: 'NEET Previous Papers',
    description: 'Solve NEET previous year question papers to understand the exam difficulty and improve problem-solving skills.',
    category: 'neet',
    type: 'papers',
    exam: 'NEET',
    class: ['class12'],
    icon: '📑',
  },
  {
    id: 9,
    title: 'JEE Physics Formulae',
    description: 'Quick reference list of important physics formulas for JEE. Helps you revise key concepts and solve problems faster.',
    category: 'jee',
    type: 'notes',
    exam: 'JEE',
    class: ['class11', 'class12'],
    icon: '⚛️',
  },
  {
    id: 10,
    title: 'JEE Main Mock Tests',
    description: 'Practice JEE Main mock tests in a real exam-style format. Improve speed, accuracy, and exam readiness.',
    category: 'jee',
    type: 'mocks',
    exam: 'JEE',
    class: ['class12'],
    icon: '🧮',
  },
  {
    id: 11,
    title: 'CUET Prep Material',
    description: 'Study notes, practice questions, and guides for CUET exams. Helpful resources to prepare for university entrance tests.',
    category: 'cuet',
    type: 'guides',
    exam: 'CUET',
    class: ['class12'],
    icon: '🎓',
  },
  {
    id: 12,
    title: 'Class 12 Study Guides',
    description: 'Simple study guides and important notes for Class 12 subjects. Great for quick revision and better exam preparation.',
    category: 'boards',
    type: 'guides',
    exam: 'CBSE',
    class: ['class12'],
    icon: '📚',
  },
];

export const ARTICLES = [
  {
    id: 1,
    title: 'How To Prepare For NEET In 6 Months',
    category: 'NEET GUIDE',
    date: 'MAR 13, 2026',
    excerpt: 'Strategic preparation plan to crack NEET in just 6 months.',
  },
  {
    id: 2,
    title: 'Top Study Strategies To Crack JEE Main',
    category: 'STUDY TIPS',
    date: 'MAR 14, 2026',
    excerpt: 'Proven study strategies used by JEE toppers.',
  },
  {
    id: 3,
    title: 'How To Build An Effective Daily Study Routine',
    category: 'STUDY TIPS',
    date: 'MAR 15, 2026',
    excerpt: 'Build a consistent study routine for better results.',
  },
  {
    id: 4,
    title: 'Best Study Plan For Class 12 Board Exams',
    category: 'CBSE GUIDE',
    date: 'MAR 15, 2026',
    excerpt: 'Complete study plan for Class 12 board exam preparation.',
  },
];

export const NEWS_ITEMS = [
  {
    id: 1,
    title: 'Top Study Strategies To Crack JEE Main',
    category: 'EXAM UPDATE',
    date: 'APR 05, 2026',
  },
  {
    id: 2,
    title: 'CBSE Releases Updated Exam Pattern For Class 10',
    category: 'EXAM UPDATE',
    date: 'APR 03, 2026',
  },
  {
    id: 3,
    title: 'CUET 2026 Registration Process Begins',
    category: 'EXAM UPDATE',
    date: 'APR 01, 2026',
  },
];

export const FAQS = [
  {
    id: 1,
    category: 'General',
    question: 'Is all content really free on this website?',
    answer: 'Yes, all study materials on our platform are completely free for students. We believe in making quality education accessible to everyone.',
  },
  {
    id: 2,
    category: 'General',
    question: 'Do you provide any paid courses or video lectures?',
    answer: 'Currently, all our resources are free. We may introduce premium content in the future, but the core study materials will remain free.',
  },
  {
    id: 3,
    category: 'Content',
    question: 'What type of study material is available?',
    answer: 'We provide study notes, mock tests, previous year papers, NCERT books, question banks, and comprehensive study guides.',
  },
  {
    id: 4,
    category: 'Content',
    question: 'Which classes or exams do you cover?',
    answer: 'We cover CBSE, NEET, JEE, CUET, and other boards. Materials are available for Class 10, 11, and 12.',
  },
  {
    id: 5,
    category: 'Access',
    question: 'Do I need to create an account to download PDFs?',
    answer: 'No account is required. You can access and download all materials directly without registration.',
  },
  {
    id: 6,
    category: 'Content',
    question: 'Is your content updated regularly?',
    answer: 'Yes, we regularly update our content to align with the latest exam patterns and NCERT syllabus.',
  },
];
